**Bài tập 1 và 2 thuộc đề 1**

- Bài tập 1: Cho 1 bảng dữ liệu, yêu cầu:
  - Chuẩn hoá dữ liệu
  - Dự đoán kết quả (0 or 1) của tập value cho trước (cần chuẩn hoá tập value phù hợp với pp được chọn ở ý 1)
  - Sử dụng thuật toán Naive Bayes để dự đoán kết quả (0 or 1) của tập value cho trước


- Chuẩn hoá

In [29]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
#dữ liệu giả
data = {
    'ID': [1, 2, 3, 4, 5,6,7,8,9,10,11,12],
    'Age': [28,25, 57, 60, 55, 56,45,34,47,68,38,42],
    'Income': [12000, 11000, 17000, 7000, 4200,3700,4600,6800,8600,9000,8000,6700],
    'Student': ['No','No','No','No', 'Yes', 'Yes', 'Yes','No', 'Yes', 'Yes','Yes','No'],
    'Credit_Rating': [0.4, 0.7, 0.3, 0.4,0.45, 0.9,0.88,0.46,0.45,0.69,0.9,0.89],
    'Buy_Computer': ['No','No','Yes','Yes','Yes', 'No', 'Yes', 'No', 'Yes','Yes','Yes','Yes']
}
df = pd.DataFrame(data)


In [33]:
# Mã hóa biến Student thành số (dummy variable)
df['Student'] = df['Student'].apply(lambda x: 1 if x == 'Yes' else 0)

# Áp dụng MinMaxScaler để chuẩn hóa dữ liệu
min_max = MinMaxScaler()
features = ['Age', 'Income', 'Credit_Rating']
df_scaled = df.copy()  # Tạo một bản sao của DataFrame gốc

df_scaled[features] = min_max.fit_transform(df[features])

df_scaled

ID       Age    Income  Student  Credit_Rating Buy_Computer
0    1  0.069767  0.624060        0       0.166667           No
1    2  0.000000  0.548872        0       0.666667           No
2    3  0.744186  1.000000        0       0.000000          Yes
3    4  0.813953  0.248120        0       0.166667          Yes
4    5  0.697674  0.037594        0       0.250000          Yes
5    6  0.720930  0.000000        0       1.000000           No
6    7  0.465116  0.067669        0       0.966667          Yes
7    8  0.209302  0.233083        0       0.266667           No
8    9  0.511628  0.368421        0       0.250000          Yes
9   10  1.000000  0.398496        0       0.650000          Yes
10  11  0.302326  0.323308        0       1.000000          Yes
11  12  0.395349  0.225564        0       0.983333          Yes

In [34]:
import numpy as np


all_features = ['Age', 'Income','Student', 'Credit_Rating']

df_scaled['Buy_Computer'] = df_scaled['Buy_Computer'].apply(lambda x: 1 if x == 'Yes' else 0)

# Chuyển đổi DataFrame thành mảng numpy
data_array = df_scaled[all_features].values
y_true = df_scaled['Buy_Computer'].values

print(y_true)

# Ma trận trọng số W
W = np.array([
    [-0.81, 0.87, 0.66],
    [0.87, -0.87, -0.34],
    [-0.5, -0.88, 0.96],
    [-0.26, -0.9, -0.2]
])

# Vector trọng số v
v = np.array([0.91, -0.12, 0.89])

# Hàm kích hoạt tanh
def tanh(x):
    return np.tanh(x)

# Hàm kích hoạt sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Ngưỡng xác suất
threshold = 0.5

# Dự đoán nhãn cho mỗi mẫu dữ liệu
predicted_labels = []

for x in data_array:
    # Tính toán giá trị tại lớp ẩn
    p = tanh(np.dot(x, W))
    
    # Tính toán giá trị đầu ra
    output = sigmoid(np.dot(p, v))

    print(output.round(4))
    
    # Xác định nhãn dựa trên ngưỡng xác suất
    label = 1 if output >= threshold else 0
    predicted_labels.append(label)

print(predicted_labels)


[0 0 1 1 1 0 1 0 1 1 1 1]
0.5673
0.522
0.598
0.4756
0.4524
0.4123
0.4182
0.5007
0.503
0.4581
0.4474
0.434
[1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0]


In [32]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix

# Tính các giá trị TP, TN, FP, FN
TP = sum((y_t == 1) and (y_p == 1) for y_t, y_p in zip(y_true, predicted_labels))
TN = sum((y_t == 0) and (y_p == 0) for y_t, y_p in zip(y_true, predicted_labels))
FP = sum((y_t == 0) and (y_p == 1) for y_t, y_p in zip(y_true, predicted_labels))
FN = sum((y_t == 1) and (y_p == 0) for y_t, y_p in zip(y_true, predicted_labels))

accuracy_minmax = accuracy_score(y_true, predicted_labels)
precision_minmax = precision_score(y_true, predicted_labels)
recall_minmax = recall_score(y_true, predicted_labels)
f1_minmax = f1_score(y_true, predicted_labels)

# Ma trận nhầm lẫn (Confusion Matrix)
confusion_matrix = [[TN, FP], [FN, TP]]

# Hiển thị kết quả
results = {
    "TP": TP,
    "TN": TN,
    "FP": FP,
    "FN": FN,
    "Precision": precision_minmax,
    "Recall": recall_minmax,
    "F1-Score": f1_minmax,
    "Accuracy": accuracy_minmax,
    "Confusion Matrix": confusion_matrix
}

print("Kết quả đánh giá mô hình:")
for key, value in results.items():
    print(f"{key}: {value}")


Kết quả đánh giá mô hình:
TP: 6
TN: 0
FP: 4
FN: 2
Precision: 0.6
Recall: 0.75
F1-Score: 0.6666666666666665
Accuracy: 0.5
Confusion Matrix: [[0, 4], [2, 6]]


- Dự đoán kết quả của tập value
  - Mã hoá tập value
  - Tính khoảng cách (Euclide hoặc Cosine)

In [35]:
# Dữ liệu của điểm dữ liệu mới
new_data = {
    'ID': 6,
    'Age': 20,
    'Income': 8000,
    'Student': 1,
    'Credit_Rating': 0.85
}

# Thêm dữ liệu mới vào DataFrame
df_new = pd.DataFrame([new_data])

# Sử dụng phương thức pd.concat() để chèn dữ liệu vào df gốc
df_updated = pd.concat([df, df_new], ignore_index=True)

#chuẩn hoá lại toàn bộ dataframe (df_updated), sử dụng pp min-max
# Áp dụng MinMaxScaler để chuẩn hóa dữ liệu
min_max = MinMaxScaler()
df_updated[features] = min_max.fit_transform(df_updated[features]).round(2)
df_updated

ID   Age  Income  Student  Credit_Rating Buy_Computer
0   1  0.25    0.29        0           0.25          Yes
1   2  0.50    0.57        1           0.50           No
2   3  0.75    0.86        1           0.75          Yes
3   4  0.00    0.00        0           0.00           No
4   5  1.00    1.00        1           1.00          Yes
5   6  0.00    0.71        1           0.75          NaN

- tính toán khoảng cách


In [39]:
#bằng công thức cosine
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Chuyển đổi DataFrame thành mảng numpy để sử dụng cosine_similarity
X_train = df_scaled[['Age', 'Income', 'Student', 'Credit_Rating']].values
# Dữ liệu của điểm dữ liệu mới
new_data = {
    'ID': 6,
    'Age': 20,
    'Income': 8000,
    'Student': 1,
    'Credit_Rating': 0.85
}
#giá trị dự đoán sau chuẩn hoá
X_new = [0,0.71,1, 0.75]

df_scaled['Cosine_Distance'] = cosine_distances

# Sắp xếp các hàng theo khoảng cách tăng dần
df_sorted = df_scaled.sort_values(by='Cosine_Distance')

# Lấy K hàng đầu tiên
K = 3
nearest_neighbors = df_sorted.head(K)

# Hiển thị các hàng láng giềng gần nhất
print(f"{K} hàng láng giềng gần nhất:")
print(nearest_neighbors)

Khoảng cách cosine:
[[0.40154827]
 [0.08357052]
 [0.10686007]
 [1.        ]
 [0.14438794]]
3 hàng láng giềng gần nhất:
   ID   Age  Income  Student  Credit_Rating Buy_Computer  Cosine_Distance
1   2  0.50    0.57        1           0.50           No         0.083571
2   3  0.75    0.86        1           0.75          Yes         0.106860
4   5  1.00    1.00        1           1.00          Yes         0.144388


In [45]:
# Tính toán khoảng cách Euclid
euclidean_distances = np.sqrt(np.sum((X_train - X_new) ** 2, axis=1))

# Thêm cột khoảng cách vào DataFrame
df_scaled['Euclidean_Distance'] = euclidean_distances

In [46]:
# Sắp xếp các hàng theo khoảng cách tăng dần
df_sorted = df_scaled.sort_values(by='Euclidean_Distance')

# Lấy K hàng đầu tiên
K = 3
nearest_neighbors = df_sorted.head(K)

print("Dataframe với khoảng cách Euclidean:")
print(df_scaled['Cosine_Distance'])

# Hiển thị các hàng láng giềng gần nhất
print(f"{K} hàng láng giềng gần nhất:")
print(nearest_neighbors[['ID', 'Age', 'Income', 'Student', 'Credit_Rating', 'Buy_Computer', 'Euclidean_Distance']])

Dataframe với khoảng cách Euclidean:
0    0.401548
1    0.083571
2    0.106860
3    1.000000
4    0.144388
Name: Cosine_Distance, dtype: float64
3 hàng láng giềng gần nhất:
   ID   Age  Income  Student  Credit_Rating Buy_Computer  Euclidean_Distance
1   2  0.50    0.57        1           0.50           No            0.576281
2   3  0.75    0.86        1           0.75          Yes            0.764853
4   5  1.00    1.00        1           1.00          Yes            1.070794


Bài tập 2: Sử dụng thuật toán K-Means và phương pháp tính khoảng cách Euclide để xác định cụm

Giải tay (thủ công)

Lần 1:
- Bước 1: Chọn điểm trung tâm của cụm: Tính điểm trung tâm (centroid) của cụm trong thuật toán k-means được tính theo công thức:
$$
m_i = \frac{1}{|C_i|} \sum_{\mathbf{x}_i \in C_i} \mathbf{x}_i
$$  
  > - m_i là điểm trung tâm của cụm C_i.
  > - |C_i| là số lượng điểm trong cụm C_i.
  > - X_i là điểm dữ liệu trong cụm C_i
  > - vd: cho cụm C1 = {(1,2), (2,3), (3,1)}, điểm trung tâm cụm C1: m_c1 = 1/3 * ((1,2) + (2,3) + (3,1)) = 1/3 * (6,6) = (2,2)
- Bước 2: Tính khoảng cách từ các điểm đến trung tâm các cụm, sử dụng công thức tính khoảng cách euclide (hoặc các công thức khác như cosine)
  - d(x, m_i) = ||x-m_i|| 
  - vd: cho 2 cụm C1= {(1,1), (3,3),(4,3)}, cụm C2 = {(1,2),(2,1),(3,4)} 
    => điểm trung tâm cụm C1: m_c1 = (8/3, 7/3), cụm C2: m_c2 = (2, 7/3)
    + từ điểm (1,1) tới điểm trung tâm c1: 2.13
    + từ điểm (1,1) tới điểm trung tâm c2: 1.67
    
    => điểm (1,1) thuộc cụm c2

    tương tư với các điểm khác
- Bước 3: Phân cụm lại các điểm

Lần 2: lặp lại các bước ở lần 1 ... cho đến khi không còn sự thay đổi giữa các điểm với các cụm


In [3]:
#Code tính khoảng cách euclide từ các điểm đến điểm trung tâm cụm
import numpy as np
# Hàm tính khoảng cách Euclide giữa các điểm dữ liệu và các trung tâm cụm
def compute_euclidean_distances(data_points, centroids):
    # data_points: ma trận (num_points, num_dimensions)
    # centroids: ma trận (num_clusters, num_dimensions)
    # Tính khoảng cách Euclide cho từng cặp điểm dữ liệu và trung tâm cụm
    distances = np.linalg.norm(data_points[:, np.newaxis, :] - centroids[np.newaxis, :, :], axis=2)
    return distances

# Hàm để tìm cụm gần nhất cho mỗi điểm dữ liệu
def assign_clusters(distances):
    # Tìm chỉ số của cụm gần nhất (min distance)
    return np.argmin(distances, axis=1)

# Ví dụ minh họa
if __name__ == '__main__':
    # Giả sử chúng ta có các điểm dữ liệu trong không gian 2D
    data_points = np.array([
        [1.0, 1.0],
        [1.0, 2.0],
        [2.0, 1.0],
        [3.0, 3.0],
        [3.0, 4.0],
        [4.0, 3.0]
    ])
    # Và có hai trung tâm cụm
    centroids = np.array([
        [8/3, 7/3],
        [2, 7/3]
    ])
    # Tính khoảng cách Euclide
    distances = compute_euclidean_distances(data_points, centroids)
    
    # In ra khoảng cách từ các điểm dữ liệu đến từng trung tâm cụm
    print("Distances:")
    print(distances)    
    # # Xác định cụm gần nhất cho mỗi điểm dữ liệu
    # cluster_assignments = assign_clusters(distances)
    # # In ra kết quả phân cụm
    # print("\nCluster assignments:")
    # print(cluster_assignments)


Distances:
[[2.13437475 1.66666667]
 [1.69967317 1.05409255]
 [1.49071198 1.33333333]
 [0.74535599 1.20185043]
 [1.69967317 1.94365063]
 [1.49071198 2.10818511]]


- **Code để xác định điểm trung tâm và phân cụm**

In [5]:
import numpy as np

# Hàm tính khoảng cách Euclide giữa các điểm dữ liệu và các trung tâm cụm
def compute_euclidean_distances(data_points, centroids):
    # data_points: ma trận (num_points, num_dimensions)
    # centroids: ma trận (num_clusters, num_dimensions)
    # Tính khoảng cách Euclide cho từng cặp điểm dữ liệu và trung tâm cụm
    distances = np.linalg.norm(data_points[:, np.newaxis, :] - centroids[np.newaxis, :, :], axis=2)
    
    return distances

# Hàm cập nhật trung tâm cụm dựa trên phân cụm hiện tại
def update_centroids(data_points, cluster_assignments, num_clusters):
    new_centroids = np.zeros((num_clusters, data_points.shape[1]))
    for k in range(num_clusters):
        # Lấy các điểm dữ liệu thuộc cụm k
        cluster_points = data_points[cluster_assignments == k]
        # Tính trung bình của các điểm dữ liệu này để cập nhật trung tâm cụm k
        if len(cluster_points) > 0:
            new_centroids[k] = np.mean(cluster_points, axis=0)
    return new_centroids

# Hàm phân cụm K-means
def kmeans(data_points, initial_centroids, max_iters=100):
    num_clusters = initial_centroids.shape[0]
    centroids = initial_centroids
    
    for i in range(max_iters):
        # Bước 1: Tính khoảng cách từ các điểm dữ liệu đến các trung tâm cụm hiện tại
        distances = compute_euclidean_distances(data_points, centroids)
        
        # Bước 2: Gán lại các điểm dữ liệu vào các cụm dựa trên khoảng cách ngắn nhất
        cluster_assignments = np.argmin(distances, axis=1)
        
        # In kết quả sau mỗi lần lặp
        print(f"Iteration {i + 1}:")
        print("Centroids:")
        print(centroids)
        print("Cluster assignments:")
        print(cluster_assignments)
        print("------------------------")
        
        # Bước 3: Cập nhật lại các trung tâm cụm dựa trên phân cụm hiện tại
        new_centroids = update_centroids(data_points, cluster_assignments, num_clusters)
        
        # Bước 4: Kiểm tra điều kiện dừng (ví dụ: trung tâm cụm không thay đổi đáng kể)
        if np.allclose(new_centroids, centroids):
            break
        
        # Cập nhật trung tâm cụm mới
        centroids = new_centroids
    
    return centroids, cluster_assignments

# Ví dụ minh họa
if __name__ == '__main__':
    data_points = np.array([
        [1.0, 1.0],
        [1.0, 2.0],
        [2.0, 1.0],
        [3.0, 3.0],
        [3.0, 4.0],
        [4.0, 3.0]
    ])
    
    # Khởi tạo các trung tâm cụm ban đầu (có thể tự tính tay (cách tính ở bài 2 -> bước 1))
    initial_centroids = np.array([
        [8/3, 7/3],
        [2.0, 7/3]
    ])
    
    # Chạy thuật toán K-means với số lần lặp tối đa là 3
    max_iters = 3
    final_centroids, cluster_assignments = kmeans(data_points, initial_centroids, max_iters=max_iters)
    
    # In ra kết quả cuối cùng
    print("\nFinal centroids:")
    print(final_centroids)
    print("\nFinal cluster assignments after", max_iters, "iterations:")
    print(cluster_assignments)


Iteration 1:
Centroids:
[[2.66666667 2.33333333]
 [2.         2.33333333]]
Cluster assignments:
[1 1 1 0 0 0]
------------------------
Iteration 2:
Centroids:
[[3.33333333 3.33333333]
 [1.33333333 1.33333333]]
Cluster assignments:
[1 1 1 0 0 0]
------------------------

Final centroids:
[[3.33333333 3.33333333]
 [1.33333333 1.33333333]]

Final cluster assignments after 3 iterations:
[1 1 1 0 0 0]


**Bài tập 3 và 4 thuộc đề 66**

Bài tập 3: Neural network (Sử dụng code để tính) - đến ý dự đoán nhãn

In [55]:
#tiền xử lí dữ liệu
#Min-Max
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
df = pd.read_excel('D:\data_test.xlsx')
min_max = MinMaxScaler()
column = ['x1', 'x2', 'x3', 'x4']
df[column] = min_max.fit_transform(df[column]).round(2)
df

x1    x2    x3    x4  y
0   0.25  0.86  0.12  0.00  0
1   0.21  0.59  0.10  0.07  0
2   0.17  0.55  0.15  0.20  0
3   0.00  0.64  0.00  0.07  0
4   0.08  0.55  0.22  0.07  0
5   0.21  0.59  0.10  0.13  0
6   0.46  1.00  0.12  0.20  0
7   0.33  0.77  0.17  0.20  0
8   0.21  0.55  0.12  0.07  0
9   0.38  0.91  0.10  0.07  0
10  0.38  0.18  0.83  0.73  1
11  0.62  0.36  0.88  0.87  1
12  0.42  0.14  0.71  0.67  1
13  0.67  0.00  0.85  0.93  1
14  0.42  0.36  0.76  0.80  1
15  0.58  0.00  0.73  0.60  1
16  1.00  0.45  0.90  0.87  1
17  0.58  0.23  1.00  1.00  1
18  0.42  0.23  0.78  0.80  1
19  0.42  0.32  0.63  0.80  1

In [60]:
import numpy as np
#remove y feature
df_del = df.copy()
df_del = df_del.drop(columns='y',axis=1)
#chuyển dataframe thành numpy
df_del = df_del.to_numpy()
# Hàm tính p_i
def compute_pi(data, W):
    # data là ma trận dữ liệu, mỗi hàng là một điểm dữ liệu
    # W là ma trận trọng số
    # b là vector bias
    # Tính p_i cho mỗi điểm dữ liệu
    p = np.dot(data, W) 
    return p

# Hàm kích hoạt tanh
def tanh_activation(p):
    return np.tanh(p)
#đầu vào của cái đít    
def compute_output(p, v):
    # p là ma trận sau khi đã áp dụng tanh cho lớp ẩn
    # v là vector trọng số cho lớp đầu ra
    # Tính o cho mỗi hàng của p
    o = np.dot(p, v)
    return o
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Hàm kích hoạt sigmoid với ngưỡng
def sigmoid_activation(o):
    sigmoid_o = sigmoid(o)
    return sigmoid_o

# Ví dụ minh họa
# Ma trận trọng số và vector bias (ví dụ đơn giản)
W = np.array([[0.51, 0.45, 0.12], [0.65, -0.11, 0.34],[-0.5, -0.88, 0.46],[-0.26,0.24,-0.2]])  
v = np.array([0.91, -0.67, 0.89])  # Vector v 

# Tính p_i cho tất cả các điểm dữ liệu
p = compute_pi(df_del, W)

# Định dạng số hiển thị
np.set_printoptions(precision=4, suppress=True)

# Áp dụng hàm kích hoạt tanh
activation_tanh = tanh_activation(p)

# Tính giá trị đầu ra o
o = compute_output(activation_tanh, v)

# Áp dụng hàm sigmoid và quyết định nhãn
sigmoid_o = sigmoid_activation(o)

In [53]:
print(p)

[[ 0.6265 -0.0877  0.3776]
 [ 0.4224 -0.0416  0.2578]
 [ 0.3172 -0.068   0.2364]
 [ 0.3978 -0.0536  0.2036]
 [ 0.2701 -0.2013  0.2838]
 [ 0.4068 -0.0272  0.2458]
 [ 0.7726  0.0394  0.4104]
 [ 0.5318 -0.0378  0.3396]
 [ 0.3864 -0.0548  0.2534]
 [ 0.7171 -0.0003  0.387 ]
 [-0.294  -0.404   0.3426]
 [-0.116  -0.3262  0.4276]
 [-0.224  -0.2904  0.2906]
 [-0.3251 -0.2233  0.2854]
 [-0.1398 -0.3274  0.3624]
 [-0.2252 -0.2374  0.2854]
 [ 0.1263 -0.1827  0.513 ]
 [-0.3147 -0.4043  0.4078]
 [-0.2343 -0.3307  0.3274]
 [-0.1008 -0.2086  0.289 ]]


In [50]:
print(activation_tanh)

[[ 0.5556 -0.0875  0.3606]
 [ 0.399  -0.0416  0.2522]
 [ 0.307  -0.0679  0.2321]
 [ 0.3781 -0.0535  0.2008]
 [ 0.2637 -0.1986  0.2764]
 [ 0.3858 -0.0272  0.241 ]
 [ 0.6484  0.0394  0.3888]
 [ 0.4868 -0.0378  0.3271]
 [ 0.3683 -0.0547  0.2481]
 [ 0.6151 -0.0003  0.3688]
 [-0.2858 -0.3834  0.3298]
 [-0.1155 -0.3151  0.4033]
 [-0.2203 -0.2825  0.2827]
 [-0.3141 -0.2197  0.2779]
 [-0.1389 -0.3162  0.3473]
 [-0.2215 -0.233   0.2779]
 [ 0.1256 -0.1807  0.4723]
 [-0.3047 -0.3836  0.3866]
 [-0.2301 -0.3191  0.3162]
 [-0.1005 -0.2056  0.2812]]


In [74]:
print(o)

[0.8852 0.6154 0.5314 0.5587 0.6191 0.5837 0.9097 0.7594 0.5926 0.8882
 0.2903 0.465  0.2404 0.1087 0.3946 0.2019 0.6557 0.3238 0.2858 0.2966]


In [78]:
# Ngưỡng xác suất
threshold = 0.5

# Dự đoán nhãn cho mỗi mẫu dữ liệu
y_pred = []

#in giá trị nhãn
for x in sigmoid_o:
  label = 1 if x >= threshold else 0
  y_pred.append(label)
y_pred

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
# 1c
# Tính các giá trị TP, TN, FP, FN
TP = sum((y_t == 1) and (y_p == 1) for y_t, y_p in zip(y_true, y_pred))
TN = sum((y_t == 0) and (y_p == 0) for y_t, y_p in zip(y_true, y_pred))
FP = sum((y_t == 0) and (y_p == 1) for y_t, y_p in zip(y_true, y_pred))
FN = sum((y_t == 1) and (y_p == 0) for y_t, y_p in zip(y_true, y_pred))

# Tính Precision, Recall, F1-Score, Accuracy
precision = TP / (TP + FP) if (TP + FP) != 0 else 0
recall = TP / (TP + FN) if (TP + FN) != 0 else 0
f1_score = 2 * precision * recall / (precision + recall) if (precision + recall) != 0 else 0
accuracy = (TP + TN) / (TP + TN + FP + FN)

# Ma trận nhầm lẫn (Confusion Matrix)
confusion_matrix = [[TN, FP], [FN, TP]]

# Hiển thị kết quả
results = {
    "TP": TP,
    "TN": TN,
    "FP": FP,
    "FN": FN,
    "Precision": precision,
    "Recall": recall,
    "F1-Score": f1_score,
    "Accuracy": accuracy,
    "Confusion Matrix": confusion_matrix
}

print("Kết quả đánh giá mô hình:")
for key, value in results.items():
    print(f"{key}: {value}")

Bài tập 4: KNN (Chưa làm)

In [92]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

#điểm cần dự đoán
df_predict = pd.DataFrame({
    'x1': [5.1, 5.5, 5.5],
    'x2': [3.4, 4.2, 2.6],
    'x3': [1.5, 1.4, 4.4],
    'x4': [0.2, 0.2, 1.2]
})
df_cau2 = df.copy()
# Áp dụng scaler đã được fit trên df để chuẩn hóa df_predict (dữ liệu cần dự đoán)
df_predict_normalized = pd.DataFrame(min_max.transform(df_predict), columns=df_predict.columns)

# Chia dữ liệu huấn luyện
X = df_cau2.drop('y', axis=1) 
y = df_cau2['y']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Khởi tạo mô hình KNN
knn = KNeighborsClassifier(n_neighbors=3)  # Số láng giềng K = 3, bạn có thể điều chỉnh số này

# Huấn luyện mô hình với dữ liệu huấn luyện
knn.fit(X_train, y_train)

# Dự đoán nhãn cho tập dữ liệu dự đoán
predictions = knn.predict(df_predict_normalized)

# In kết quả dự đoán
print(predictions)


[0 0 1]
